openapi: 3.0.0
info:
 version: '1.0'
 title: 'LBAW Usless Web API'
 description: 'Web Resources Specification (A7) for Usless'

servers:
- url: 
 description: Production server

externalDocs:
 description: Find more info here.
 url: 

tags:
 - name: 'M01: Authentication and Individual Profile'
 - name: 'M02: Publishing posts, comments and reacts'
 - name: 'M03: Friendship'
 - name: 'M04: Groups'
 - name: 'M05: User Administration and Static pages'



paths:
  /login:
   get:
     operationId: R01
     summary: 'R01: Login Form'
     description: 'Provide login form.'
     tags:
       - 'M01: Authentication and Individual Profile'
     responses:
       '200':
         description: 'Show Log-in'
   post:
     operationId: R02
     summary: 'R02: Login Action'
     description: 'Processes the login form submission.'
     tags:
       - 'M01: Authentication and Individual Profile'  

     requestBody:
       required: true
       content:
         application/x-www-form-urlencoded:
           schema:
             type: object
             properties:
               email:          
                 type: string
               password:    
                 type: string
             required:
                  - email
                  - password
     responses:
                '302':
                    description: 'Redirect after login'
                    headers:
                      Location:
                        schema:
                          type: string
                        examples:
                          302Success:
                              description: 'Ok. Redirect to Home Page'
                              value: '/cards'
                          302Error:
                              description: 'Failed Authentication. Redirect to login form.'
                              value: '/login'

  /logout:
        post:
            operationId: R03
            summary: 'R03: Logout Action'
            description: 'Logout the current authenticated user. Access: USR'
            tags:
                - 'M01: Authentication and Profile'
            responses:
                '302':
                    description: 'Redirect after processing logout.'
                    headers:
                        Location:
                          schema:
                            type: string
                          examples:
                              302Success:
                                  description: 'Successful logout. Redirect to homepage.'
                                  value: '/login'

 /register:
        get:
            operationId: R04
            summary: 'R04: Register Form '
            description: 'Provide signup form. Access: PUB'
            tags:
              - 'M01: Authentication and Profile'
            responses:
              '200':
                description: 'Ok. Show sign-up form UI.'

        post:
            operationId: R05
            summary: 'R05: Register Action'
            description: 'Signup to the website'
            tags:
                - 'M01: Authentication and Profile'
            
            requestBody:
                    required: True
                    content:
                        application/x-www-form-urlencoded:
                            schema:
                                type: object
                                properties:
                                    username:
                                        type: string
                                    email:
                                        type: string
                                    password:
                                        type: string
                                required:
                                    - username
                                    - email
                                    - password
            responses:
                '302':
                    description: 'Redirect after processing signup credentials.'
                    headers:
                      Location:
                        schema:
                          type: string
                        examples:
                            302Success:
                                description: 'Successful credential insertion.Redirect to user'
                                value: '/username/{id}'
                            302Error: 
                                description: 'Failed credential insertion. Redirect to signup form'
                                value: '/register'

     /profileShow/{username}:
          get:
            operationId: R06
            summary: 'R06: View Profile'
            description: 'Show the individual user profile. Access: USR'
          tags:
            - 'M01: Authentication and Individual Profile'

          parameters:
            -in: path
            name: username
            schema:
              type: string
            required: true

          responses:
            '200':
              description: 'Ok. Show User Profile UI'
  
     /postInsert:
       post:
        operationId: R08
        summary: 'R08: Publish Post'
        description: 'Insert a new Post. Access: USR'
        tags: 
          - 'M02: Publishing posts, comments and reacts'

        requestBody:
                required: True
                content:
                    application/x-www-form-urlencoded:
                        schema:
                            type: object
                            properties:
                                id:
                                    type: integer
                                id_user:
                                    type: integer
                                content:
                                    type: string
                                post_state:
                                    type: integer
                                post_date:
                                    type: string
                                id_groups:
                                    type: integer  
                            required:
                                - id
                                - id_user
                                - content
                                - post_state
                                - post_date
                                - id_groups
                responses:
                '200':
                  description: 'Ok. Post inserted'
    
      /postDelete/{id}:
        delete:
            operationId: R09
            summary: 'R09: Delete Post'
            description: 'Processes the deletion of a post. Access: USR' 
            tags: 
            - 'M02: Publishing posts, comments and reacts'

            parameters:
              - in: path
                name: id
                schema:
                  type: integer
                required: true


            responses:
                '302':
                    description: 'Redirect after deleting post'
                    headers:
                        Location:
                            schema:
                                type: string
                            examples:
                                302Success:
                                    description: 'Sucessfull deletion. Redirected to the specific question page.'
                                    value: '/cards'

        postUpdate/{id}:
                              
        post:
          operationId: R10
          summary: 'R10: Edit Post'
          description: 'Edit Post. Access: USR'
          tags: 
            - 'M02: Publishing posts, comments and reacts'

          requestBody:
                  required: True
                  content:
                      application/x-www-form-urlencoded:
                          schema:
                              type: object
                              properties:
                                  id:
                                      type: integer
                                  id_user:
                                      type: integer
                                  content:
                                      type: string
                                  post_state:
                                      type: integer
                                  post_date:
                                      type: string
                                  id_groups:
                                      type: integer  
                              required:
                                  - id
                                  - id_user
                                  - content
                                  - post_date
                                 
                  responses:
                  '200':
                    description: 'Ok. Post edited'          







